### ISSUE TITLE
`organization_id` cannot be set in `POST /user`

### ISSUE THREAD

**Issue by mellesies** [IKNL/vantage6-server#19]
Reported by Djura Smits.

When POSTing as root:
```POST /user
{
  "firstname": "user",
  "lastname": "lastname",
  "password": "hehehe",
  "organization_id": "1",
  "username": "anotheradmin",
  "roles": ["admin"]
}
```

`organization_id` from `root` will be used (which is probably not set).

**Comment by bartvanb** [comment]
This issue appears to have been resolved in the commits stated above. I just verified that this is working as expected in the master branch.

One question though: it is currently possible to create users for organization_ids that do not represent an organization. Maybe we should throw an error in these cases? (if organization is created later on, a user might have unintended access to it)
