### ISSUE TITLE
Add option to vserver: --version

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-server#2]
Having the commands `vnode --version` and `vnode-local --version` would be helpful for providing support.

### vserver-local
- for a regular installation, `vserver.__version__` should be returned. 
- for an editable installation, `vserver.__version__` should be returned together with the (short) hash of the current commit (if available) and the current branch (if available).

### vserver
- see above; _and_
- the output for `vserver-local`, run within docker, should be added.

**Comment by intGRen** [comment]
Fixed in: d939b0c395b02de9c680f7ca107da624a718cd2f and 27b1394a6ab0d96a2435065b805a782f74ff5dd2
