### ISSUE TITLE
ipython dependency incompatible with jupyter notebook

### ISSUE THREAD

**Issue by jvsoest** [IKNL/vantage6-server#37]
When using jupyter notebook for researcher/client examples, the notebook breaks when installing the Vantage6 package (`pip install vantage6`). This happens as the IPython version is downgraded to 7.13.0, which breaks cell execution in jupyter. After forcing to install ipython 7.26.0 this behaviour stops, and everything works correctly.

Suggestion to upgrade the IPython version, although I cannot oversee the issues it may cause on the server side.

**Comment by jvsoest** [comment]
Or if I only need the client, would using the package "vantage6-client" solve this issue?

**Comment by frankcorneliusmartin** [comment]
Hi Johan, 

Thanks for reaching out! 

Installing the `vantage6-client` package would probably sufficient in your case. This would give you the Client class `from vantage6.client import Client`. 

The iPython dependency is for the database administration tool for the server. So not intended for use with Jupyter notebooks. However I think it would be good to upgrade the dependencies.

**Comment by jvsoest** [comment]
Perfect! tested this today as well (see the Jupiter notebooks at https://github.com/MaastrichtU-BISS/Vantage6-Researcher-Notebooks).
Closing this non-issue 😉
