### ISSUE TITLE
Node status is not always correct

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-server#42]
It seems like the server disconnect event is triggered after a new reconnect

**Comment by bartvanb** [comment]
Just updated the pull requests to include the comments. 

@frankcorneliusmartin you mentioned that the `ContainerKillListener` class may be used in the server as well. I briefly looked into this and the Flask SocketIO server already does something like this itself. Therefore, I have not made any changes to the server repo.
