### ISSUE TITLE
Server behind NGINX produces "(insecure_transport) OAuth 2 MUST utilize https." when obtaining VPN config

### ISSUE THREAD

**Issue by frankcorneliusmartin** [IKNL/vantage6-server#51]
This happens because the SSL is terminated at the proxy. The transport between NGINX (or any other reverse proxy app) <-> vantage6-server is in this case an insecure connection.  This is acceptable as both NGINX and the vantage6-server are on the same machine. 

A solution would be to set the environment variable `OAUTHLIB_INSECURE_TRANSPORT` which is used by the OATH library:

```python
import os
os.environ['OAUTHLIB_INSECURE_TRANSPORT'] = '1'
```

https://github.com/DavidMStraub/homeassistant-homeconnect/issues/3

Another (better) solution would be to use the `ProxyFix`:
https://werkzeug.palletsprojects.com/en/1.0.x/middleware/proxy_fix/#x-forwarded-for-proxy-fix

Some other projects facing the same issue:
https://github.com/weibeu/Flask-Discord/issues/3
https://github.com/DavidMStraub/homeassistant-homeconnect/issues/3

**Comment by frankcorneliusmartin** [comment]
@dsmits is this still an issue or was this resolved by adding `https://` to the VPN server URL?

**Comment by dsmits** [comment]
Sorry for not answering this. It was indeed resolved by `https://`
